@startuml

title 信長の野望Online 逢魔依頼予報ボット クラス図

namespace system {
  class DateTime
}

namespace Nol {
  namespace Ouma {
    class QuestInfo {
      string placeName
      string questName
    }

    class Forecaster {
      +QuestInfo getForecastByDayTime(daytime dayTime)
    }

    Forecaster --> QuestInfo

    Forecaster ...> DateTime
  }

@enduml
