@startuml

autoactivate on

title 信長の野望Online 逢魔依頼予報ボット シーケンス図

box "nol_ouma"
  participant Forecaster
end box

[-> Forecaster ** : create

[-> Forecaster : getForecastByDayTime(dayTime)
alt dayTime in dict
  Forecaster -> Forecaster : questInfo = dict[dayTime]
  return
else dayTime < minimum dayTime in dict
  Forecaster -> Forecaster : questInfo = error
  return
else Wednesday && before maintenance
  Forecaster -> Forecaster : getForecastByDayTime(3 weeks before dayTime before maintenance)
  return
else
  Forecaster -> Forecaster : next of getForecastByDayTime(1 day before dayTime) in dict
  return
end
return questInfo

[-> Forecaster !! : delete

@enduml
